# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  # CI
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
